config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :games, except: :destroy do
    patch :join
    patch :move
    get :poll
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :players

  validates :canvas_height, presence: true
  validates :canvas_width, presence: true
  validates :player_count, presence: true
  validate :image_size_is_correct

  def joinable?
    players.count < player_count
  end

  COLORS = %w[ #000 #00f #0f0 #0ff #f00 #f0f #ff0 #fff ]

  def get_pixel(row, column)
    COLORS[image[(row * canvas_width) + column].ord]
  end

  def set_pixel(row, column, color)
    image[(row * canvas_width) + column] = (COLORS.index(color) || 0).chr
  end

  def resolve_moves!
    if players.where(current_move: nil).any?
      raise 'Cannot resolve moves, still waiting on one or more players'
    else
      # TODO make sure moves are only made on spaces that are currently black
      moves = {}
      players.each do |player|
        if moves[[player.row, player.column]].nil?
          moves[[player.row, player.column]] = player.color
        elsif moves[[player.row, player.column]] != player.color
          moves[[player.row, player.column]] = '#000'
        end
      end
      moves.each_pair do |(row, column), color|
        set_pixel(row, column, color)
      end
      save!
      players.update_all(current_move: nil)
    end
  end

  def initialize_image
    self.image = 0.chr * canvas_width * canvas_height
  end

  def describe
    "#{canvas_height}x#{canvas_width} game with #{players.count}/#{player_count} players"
  end

  private

  def image_size_is_correct
    if image.size != canvas_width * canvas_height
      errors.add(:image, "must have the expected dimentions")
    end
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :game
  belongs_to :user

  MOVE_PATTERN = /(\d+) (\d+) (#[0f]{3})/

  # TODO: validate and guarantee in DB that game_id, user_id is unique

  validates :current_move,
            format: { with: MOVE_PATTERN, message: 'invalid move' },
            allow_nil: true

  %w[ row column color ].each do |move_aspect|

    define_method move_aspect do
      get_instance_variables_from_current_move
      instance_variable_get("@#{move_aspect}")
    end

    define_method "#{move_aspect}=" do |value|
      instance_variable_set("@#{move_aspect}", value)
      set_current_move_from_instance_variables
    end

  end

  private

  def get_instance_variables_from_current_move
    if MOVE_PATTERN =~ current_move
      @row = $1.to_i
      @column = $2.to_i
      @color = $3
    elsif current_move.present?
      raise "Cannot parse invalid move: #{current_move.inspect}"
    end
  end

  def set_current_move_from_instance_variables
    move = "#{row} #{column} #{color}"
    self.current_move = move if MOVE_PATTERN =~ move
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_action :authenticate_user!

  before_action except: :index do
    id = params[:id] || params[:game_id]
    if id
      @game = Game.find(id)
    else
      @game = Game.new
    end
  end

  def index
    @games = Game.all
  end

  def show
    if @game.joinable?
      render :join
    else
      render :show
    end
  end

  def new
  end

  def create
    @game.player_count = 2
    @game.assign_attributes(
      params.require(:game).permit(:canvas_height, :canvas_width, :player_count)
    )
    @game.canvas_width = @game.canvas_height if @game.canvas_width.nil?
    @game.initialize_image
    if @game.save
      @game.players.create(user: current_user)
      redirect_to @game
    else
      render :new
    end
  end

  def join
    # TODO check for validations
    @game.players.create(user: current_user) if @game.joinable?
    redirect_to @game
  end

  def move
    @player = @game.players.find_by(user_id: current_user.id)
    if @player
      @player.update(params.require(:move).permit(:row, :column, :color))
      # TODO make sure moves are only made on spaces that are currently black
      if @game.players.where(current_move: nil).any?
        if params[:format] == 'json'
          render json: { update: false }
        else
          flash[:notice] = 'Your move has been locked in'
          redirect_to @game
        end
      else
        @game.resolve_moves!
        if params[:format] == 'json'
          render json: { update: true }
        else
          redirect_to @game
        end
      end
    else
      flash[:alert] = 'You are observing this game'
      redirect_to @game
    end
  end

  def poll
    render json: {updated: @game.updated_at.to_i}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to games_path
    else
      redirect_to new_user_registration_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.haml
%h2 Games

= link_to 'new game', new_game_path

- @games.each do |game|
  %p
    = game.describe
    %br/
    - if game.joinable?
      = link_to 'join', game
    - else
      = link_to 'view', game

app/views/games/join.html.haml
%h2= @game.describe

- if @game.players.where(user_id: current_user.id).any?
  %p Waiting for more players
- else
  %p= link_to 'join', [@game, :join], method: :patch

app/views/games/new.html.haml
%h2 New Game

= form_for @game do |f|
  = f.label :canvas_height, 'Canvas Size'
  = f.number_field :canvas_height
  = f.submit

app/views/games/show.html.haml
.palette
  - Game::COLORS.each do |color|
    .color{style: "background-color: #{color};", data: {color: color}}

.game{style: "width: #{@game.canvas_width * 15}px;", data: {updated: @game.updated_at.to_i, id: @game.id}}>
  - @game.canvas_height.times do |row|
    .row<>
      - @game.canvas_width.times do |column|
        - color = @game.get_pixel(row, column)
        .pixel{style: "background-color: #{color};", data: {row: row, column: column, color: color}}<>
  .cursor.color

.instructions

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Coop
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if user_signed_in?
      %p= link_to('Logout', destroy_user_session_path, :method => :delete)
    %p.notice= notice
    %p.alert= alert
    = yield